#include "core.h"

ECS_COMPONENT_TYPE_DETAILS(EntityId);
ECS_COMPONENT_TYPE_DETAILS(bool);
ECS_COMPONENT_TYPE_DETAILS(int);
ECS_COMPONENT_TYPE_DETAILS(float);
ECS_COMPONENT_TYPE_DETAILS_ALIAS(glm::vec2, vec2);
ECS_COMPONENT_TYPE_DETAILS_ALIAS(glm::vec3, vec3);
ECS_COMPONENT_TYPE_DETAILS_ALIAS(glm::vec4, vec4);
ECS_COMPONENT_TYPE_DETAILS_ALIAS(eastl::string, string);
ECS_COMPONENT_TYPE_DETAILS(Tag);

extern const uint32_t ecs_pull_core = HASH("core").hash;